version: '3.8'

services:
  producer:
    build: ./ticket-producer
    networks:
      - taskqueue
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - rabbitmqc
  consumer:
    build: ./ticket-consumer
    networks:
      - taskqueue
    restart: always
    depends_on:
      - rabbitmqc
  rabbitmqc: 
    image: rabbitmq:alpine
    networks:
      - taskqueue

networks:
  taskqueue:
    name: taskqueue
    driver: bridge